CSS変更＋ヘッダの変更＋ロゴ修正？
coderdojo-konan/website pull request #15
Opened 2019-12-20 13:20 UTC by 7io63

#Overview
#12 の指摘事項を修正したものです。Branch間違えちゃった…

2019-12-23 06:10 UTC, yu-san-19 commented
out-of-date が出ているので修正しておきました。

2019-12-23 06:13 UTC, yum45f requested changes
スマホ(iphone 11, chrome) だと正常に表示されていないです…
修正をお願いします。

![18D1B982-4643-4687-B04C-10D31CD6EB06](https://user-images.githubusercontent.com/26282705/71339351-8b437f00-2596-11ea-9ddd-36660aa89fdf.png)
![8B72A088-61D2-474C-AC70-7DC6347F9D70](https://user-images.githubusercontent.com/26282705/71339352-8b437f00-2596-11ea-9963-c779137ea313.png)

2019-12-23 08:20 UTC, 7io63 commented
iPhoneはimageタグでのSVG表示対応していないみたいなのでｓｖｇタグにでも書き直しますね

あと、どこまでブラウザサポートするかの範囲を明確にすべきな気がする…

2019-12-23 12:06 UTC, yum45f reviewed
少し気になる点がいくつかあります！

2019-12-23 12:06 UTC, yu-san-19 commented on _includes/_navbar.html
> +		<object type="image/svg+xml" data="assets/images/index/logo.svg" height="70%" width="70%"></object>
ここ、`svg` タグじゃうまく動かない感じですか？

2019-12-23 12:06 UTC, yu-san-19 commented on _sass/_global.scss
> +  font-family: "Lato","Noto Sans JP",BlinkMacSystemFont,-apple-system,"Segoe UI",Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
フォントは基本的に Noto Sans JP を使うようにしているのですが、1番目に Lato を指定している理由を教えてください！

2019-12-23 12:09 UTC, yu-san-19 commented
> あと、どこまでブラウザサポートするかの範囲を明確にすべきな気がする…
いわゆるモダンブラウザには対応したいと思っていますが、レガシーなものについては対応する必要性はないと思っています。それの対応に対する技術的コストと、対応した結果生まれるベネフィットが対等であるとは考えられないためです。

2019-12-23 12:11 UTC, 7io63 commented on _sass/_global.scss
> +  font-family: "Lato","Noto Sans JP",BlinkMacSystemFont,-apple-system,"Segoe UI",Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
ブランドガイドラインに準拠
https://company-51033.frontify.com/d/E6KNDhunr9mR/coderdojo-style-guide-1460385526

2019-12-23 12:11 UTC, 7io63 commented on _includes/_navbar.html
> +		<object type="image/svg+xml" data="assets/images/index/logo.svg" height="70%" width="70%"></object>
クリップボードに入りきらなかったのであきらめた

2019-12-23 12:16 UTC, yu-san-19 commented on _sass/_global.scss
> +  font-family: "Lato","Noto Sans JP",BlinkMacSystemFont,-apple-system,"Segoe UI",Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
納得です！

2019-12-23 12:21 UTC, yu-san-19 commented on _includes/_navbar.html
> +		<object type="image/svg+xml" data="assets/images/index/logo.svg" height="70%" width="70%"></object>
svg に直しときますね！
あとやはりサイズが小さめなので、それもこちらで直しておきます。

2019-12-23 12:35 UTC, 7io63 commented
> > あと、どこまでブラウザサポートするかの範囲を明確にすべきな気がする…
> > いわゆるモダンブラウザには対応したいと思っていますが、レガシーなものについては対応する必要性はないと思っています。それの対応に対する技術的コストと、対応した結果生まれるベネフィットが対等であるとは考えられないためです。

あくまで閲覧できない状態にするのは反対というニュアンスです。
完全に閲覧できない状態にした時の損失が十分存在するからです。
**理由：**
参加を最終的に承諾するのはあくまで保護者です。その中にはレガシーなブラウザのみを使わざるを得ない人々が多くいるでしょう。保護者としてはＨＰは存在するがChromeのダウンロードページだとかそういったところに飛ばされたとして、参加したいと思えるでしょうか。CoderDojo Konanの信頼性を落としうる方策ですし、それは能力あるいは環境によって参加者を排斥することになりませんか？

2019-12-23 12:51 UTC, yu-san-19 commented
確かにそのような損失は存在することは認めますし、もとから認識しています。
ただ、公式サイトを見れなくても参加は可能です。Doorkeeper にも最低限な内容は記載しています。
そこを踏まえて、対応する作業量のコストと見合うかといえば、見合わないというのが個人的な感想ですね。

> 保護者としてはＨＰは存在するがChromeのダウンロードページだとかそういったところに飛ばされたとして、参加したいと思えるでしょうか。CoderDojo Konanの信頼性を落としうる方策ですし、それは能力あるいは環境によって参加者を排斥することになりませんか？

対応していない理由を書き、そこにモダンブラウザのインストール先や方法などが書かれたページを表示するという対応は考えていますが、そもそも強制リダイレクトとは一言も言っていません。これによって CoderDojo Konan の信頼性が落ちるとは考えづらいですね。
先述したように公式サイトを見れなくても参加は可能です。能力・環境によって意図的に排斥しているとはいえないと思います。

2019-12-23 12:53 UTC, 7io63 commented
> 対応していない理由を書き、そこにモダンブラウザのインストール先や方法などが書かれたページを表示するという対応は考えていますが、そもそも強制リダイレクトとは一言も言っていません。これによって CoderDojo Konan の信頼性が落ちるとは考えづらいですね。
> 先述したように公式サイトを見れなくても参加は可能です。能力・環境によって意図的に排斥しているとはいえないと思います。

納得しました。

2019-12-23 12:56 UTC, 7io63 commented on _includes/_navbar.html
> +		<object type="image/svg+xml" data="assets/images/index/logo.svg" height="70%" width="70%"></object>
そんなに小さいですか？

2019-12-24 13:29 UTC, yu-san-19 commented
iPhone での表示を無事確認しましたが、PCで見たときサイズが少し小さく見えるので、修正をお願いしたいです。
現状だとiPhoneで見たときのサイズは(上の文字の大きさは調整するとして)いい感じだと思います！

2019-12-28 12:21 UTC, yum45f approved these changes
LGTM 👍

2019-12-30 14:26 UTC, merged